version: '3'

networks:
  laravel:

services:
  server:
    image: nginx:stable-alpine
    container_name: server
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - laravel

  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - laravel
