version: '3'

networks:
  dafault:

services:
  server:
    image: nginx:stable-alpine
    container_name: ${NETWORK_NAME}_server
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - dafault

  database:
    image: mysql:5.7.22
    container_name: ${NETWORK_NAME}_database
    restart: unless-stopped
    tty: true
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - dafault

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${NETWORK_NAME}_php
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - dafault
